# bypass R CMD Check notes, related to tidyverse non-standard evaluation
# https://www.r-bloggers.com/2019/08/no-visible-binding-for-global-variable/
utils::globalVariables(c(
    "x",
    "start",
    "end",
    ":=",
    "intron_start",
    "intron_end",
    "exons",
    "xend",
    "mid",
    "index",
    "diff_type",
    "in_exons",
    "in_ref_exons",
    ".",
    # shorten_gaps()
    "width",
    "rescaled_start",
    "rescaled_end",
    "width_tx_start",
    "seqnames",
    "strand",
    "shorten_type",
    "gap_width",
    "shortened_gap_width",
    "shortened_gap_diff",
    "sum_shortened_gap_diff",
    "intron_indexes",
    "shortened_width",
    "type",
    # add_exon_number()
    "exon_number",
    "n_exons",
    # geom_junction_label_repel()
    "group",
    "median",
    "median_x",
    "median_diff",
    "x_points",
    "y_points",
    "y",
    "y_orig",
    "position_nudge_repel"
))
